version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Starting build process"
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no
